FROM node:16-alpine
ENV NODE_ENV production
WORKDIR /srv/app
RUN chown node:node /srv/app
RUN npm install --location=global @nestjs/cli
COPY --chown=node:node package*.json ./
USER node
RUN npm ci --only=production
CMD ["npm", "run", "start:dev"]
