version: '3'

services:
  knowme_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1G
        reservations:
          memory: 0M
    restart: unless-stopped
    ports:
      - '$PORT:$PORT'
    environment:
      - TZ=$TIME_ZONE
    volumes:
      - ./src:/srv/app/src
      - ./package.json:/srv/app/package.json
      - ./package-lock.json:/srv/app/package-lock.json
      - ./nest-cli.json:/srv/app/nest-cli.json
      - ./tsconfig.build.json:/srv/app/tsconfig.build.json
      - ./tsconfig.json:/srv/app/tsconfig.json
      - ./.env.development:/srv/app/.env.development
      - knowme-nest-node_modules:/srv/app/node_modules
    depends_on:
      - knowme_postgres
    links:
      - knowme_postgres
  knowme_postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=$TYPEORM_DATABASE
      - POSTGRES_USER=$TYPEORM_USERNAME
      - POSTGRES_PASSWORD=$TYPEORM_PASSWORD
    ports:
      - '$TYPEORM_PORT:$TYPEORM_PORT'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  knowme-nest-node_modules:
